#!/bin/bash

set -e

mkdir -p target
JARS="$(find target -name '*.jar')"

if [ -z "$JARS" ]; then
  echo Compiling...
  if ! mvn -DskipTests clean package > /tmp/bflog 2>&1; then
    cat /tmp/bflog
  fi
fi

java -jar target/fuzz-*.jar "$@"
